"""empty message

Revision ID: 0390f9b97d69
Revises: 6ec035551589
Create Date: 2021-03-30 04:30:21.067688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0390f9b97d69'
down_revision = '6ec035551589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('losses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('val', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submit_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('teamname', sa.String(length=20), nullable=False),
    sa.Column('submitter', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['submitter'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submit_model')
    op.drop_table('losses')
    # ### end Alembic commands ###
