"""empty message

Revision ID: 1960e6377a94
Revises: bff4ec618572
Create Date: 2021-03-30 04:45:38.966375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1960e6377a94'
down_revision = 'bff4ec618572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'losses', 'submit_model', ['model_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'losses', type_='foreignkey')
    # ### end Alembic commands ###
