"""empty message

Revision ID: 3c860f18633a
Revises: 7bec85aeda08
Create Date: 2021-04-01 14:40:15.630624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c860f18633a'
down_revision = '7bec85aeda08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False,
               existing_server_default=sa.text("'nick'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True,
               existing_server_default=sa.text("'nick'"))

    # ### end Alembic commands ###
