"""empty message

Revision ID: 454f3e4c2b59
Revises: 2f9f60a5888e
Create Date: 2021-03-30 04:17:26.220096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454f3e4c2b59'
down_revision = '2f9f60a5888e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('losses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('val', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submit_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('teamname', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submit_model')
    op.drop_table('losses')
    # ### end Alembic commands ###
