"""empty message

Revision ID: 6021d3c44010
Revises: 3c860f18633a
Create Date: 2021-04-01 14:43:57.799128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6021d3c44010'
down_revision = '3c860f18633a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit_model', schema=None) as batch_op:
        batch_op.drop_column('submitted_on')

    # ### end Alembic commands ###
