"""empty message

Revision ID: 68b12b7d6e91
Revises: 6021d3c44010
Create Date: 2021-04-01 14:44:22.401044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b12b7d6e91'
down_revision = '6021d3c44010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit_model', schema=None) as batch_op:
        batch_op.alter_column('submitted_on',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit_model', schema=None) as batch_op:
        batch_op.alter_column('submitted_on',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
