"""empty message

Revision ID: 6ec035551589
Revises: 454f3e4c2b59
Create Date: 2021-03-30 04:21:42.179067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec035551589'
down_revision = '454f3e4c2b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submit_model', sa.Column('submitter', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'submit_model', 'user', ['submitter'], ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submit_model', type_='foreignkey')
    op.drop_column('submit_model', 'submitter')
    # ### end Alembic commands ###
