"""empty message

Revision ID: bff4ec618572
Revises: 0390f9b97d69
Create Date: 2021-03-30 04:38:33.097012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff4ec618572'
down_revision = '0390f9b97d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('losses', sa.Column('model_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'losses', 'submit_model', ['model_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'losses', type_='foreignkey')
    op.drop_column('losses', 'model_id')
    # ### end Alembic commands ###
